# build stage
FROM node:16.3.0-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./src/config/index.js.example ./src/config/index.js
COPY . .
CMD ["npm", "run", "build"]

# production stage
FROM nginx:stable-alpine as production-stage
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
